defaults:
  - process: lstm
  - model: lstm
  - forecast: lstm
  - _self_

hypertune: False

raw:
  path: /home/solano_todeschini/ForeML/data/raw/test_data.csv

processed:
  dir: /home/solano_todeschini/ForeML/data/processed
  name: processed.csv
  path: ${processed.dir}/${processed.name}

final:
  dir: /home/solano_todeschini/ForeML/data/final
  name_x: final_x.csv
  name_y: final_y.csv
  path_x: ${final.dir}/${final.name_x}
  path_y: ${final.dir}/${final.name_y}

test:
  dir: /home/solano_todeschini/ForeML/data/test
  name: test_data.csv
  path: ${test.dir}/${test.name}

mlmodel:
  version: 1.0
  dir: /home/solano_todeschini/ForeML/models/
  name: ${model.type}_model_v${model.version}.h5
  path: ${model.dir}/${model.name}


results:
    dir: /home/solano_todeschini/ForeML/data/results
    name: ${model.type}_v${model.version}_results.csv
    csv_path: ${results.dir}/${results.name}
    plots_path: ${results.dir}

truevalues:
    dir: /home/solano_todeschini/ForeML/data/results
    name: ${model.type}_v${model.version}_truevalues.csv
    csv_path: ${results.dir}/${results.name}
    plots_path: ${results.dir}
